# Generated by Django 3.0.8 on 2020-08-17 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('b8437191-cb4e-49eb-9ee9-e2628aaf8287'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user_activity_id',
            field=models.CharField(default=uuid.UUID('1b0ab5a3-db96-4c07-bdc1-820aff110166'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
