# Generated by Django 3.0.8 on 2020-08-17 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200817_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user_activity_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
