# Generated by Django 3.0.8 on 2020-08-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20200817_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='activity.User'),
        ),
    ]
